[pytest]

log_file = test_conversor.log_file
log_file_level = DEBUG
log_file_mode = w
markers = 
    system: used to test the system
    unit: used to test the components
    multi: used to test with multiple components
    aprox: used to test with approximate values
    decimal: used to test with decimal values