[pytest]

log_file = test_conversor.log_file
log_file_level = DEBUG
log_file_mode = w
markers = 
    system: used to test the system
    unit: used to test the components
    wip: work in progress
    